# Generated by Django 5.1.6 on 2025-03-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('none', 'Без диплома')], default='none', max_length=20),
        ),
    ]
