# Generated by Django 5.1.6 on 2025-03-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp_books', '0002_films_trailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('💥', '💥'), ('💥💥', '💥💥'), ('💥💥💥', '💥💥💥'), ('💥💥💥💥', '💥💥💥💥'), ('💥💥💥💥💥', '💥💥💥💥💥')], default='💥', max_length=10)),
                ('choice_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='startapp_books.films')),
            ],
        ),
    ]
