# Generated by Django 5.1.6 on 2025-03-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp_books', '0003_alter_films_options_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.RemoveField(
            model_name='films',
            name='trailer',
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия'), ('Про любовь ', 'Про любовь'), ('Фантастика ', 'Фантастика'), ('Психология', 'Психология'), ('Поэма', 'Поэма'), ('Детское\\Сказка', 'Детское\\Сказка'), ('Драма', 'Драма'), ('Другое', 'Другое')], max_length=15),
        ),
    ]
